### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by a-x-** [MatteoGabriele/create-npm-package#1]
Hey,
I have a similar tool: https://github.com/a-x-/create-npm-pkg/blob/master/README.md

my todos: https://github.com/a-x-/create-npm-pkg/blob/master/README.md#todo

you might want to do too:

* add github repo creating (api)
* add npm package creating (api)
* add travis-ci setup (api)

also:
* Write tests
* gh + npm tags
* add a few different scafold types
* Add test framefork selector (jest, ava, _____)

p.s. [yeoman](https://github.com/yeoman/yo) is sad :)

**Comment by MatteoGabriele** [comment]
hey thanks for suggestions, I will implement something for unit tests and maybe travis.
Will close this and make different issues :)
